// <auto-generated />
using System;
using ExpenseTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpenseTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpenseTracker.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ExpenseTracker.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_number");

                    b.Property<DateTime>("AccountOpenDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("account_open_date");

                    b.Property<string>("BankAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_address");

                    b.Property<long>("BankContactNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("bank_contact_number");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_name");

                    b.Property<int>("LedgerId")
                        .HasColumnType("integer")
                        .HasColumnName("ledger_id");

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<decimal>("RemainingBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("remaining_balance");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("RecById");

                    b.ToTable("bank", "bank");
                });

            modelBuilder.Entity("ExpenseTracker.Models.BankTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int>("BankId")
                        .HasColumnType("integer")
                        .HasColumnName("bank_id");

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_id");

                    b.Property<DateTime>("TxnDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("txn_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("RecById");

                    b.ToTable("bank_transactions", "bank");
                });

            modelBuilder.Entity("ExpenseTracker.Models.Coa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("RecById");

                    b.ToTable("coa", "accounting");
                });

            modelBuilder.Entity("ExpenseTracker.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CrAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("cr_amount");

                    b.Property<decimal>("DrAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("dr_amount");

                    b.Property<int>("LedgerId")
                        .HasColumnType("integer")
                        .HasColumnName("ledger_id");

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("TxnDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("txn_date");

                    b.HasKey("Id");

                    b.HasIndex("LedgerId");

                    b.HasIndex("RecById");

                    b.ToTable("expenses", "accounting");
                });

            modelBuilder.Entity("ExpenseTracker.Models.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CrAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("cr_amount");

                    b.Property<decimal>("DrAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("dr_amount");

                    b.Property<int>("LedgerId")
                        .HasColumnType("integer")
                        .HasColumnName("ledger_id");

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("TxnDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("txn_date");

                    b.HasKey("Id");

                    b.HasIndex("RecById");

                    b.ToTable("income", "accounting");
                });

            modelBuilder.Entity("ExpenseTracker.Models.Ledger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("LedgerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ledger_name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("SubParentId")
                        .HasColumnType("integer")
                        .HasColumnName("sub_parent_id");

                    b.HasKey("Id");

                    b.HasIndex("RecById");

                    b.ToTable("ledger", "accounting");
                });

            modelBuilder.Entity("ExpenseTracker.Models.Liability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CrAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("cr_amount");

                    b.Property<decimal>("DrAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("dr_amount");

                    b.Property<int>("LedgerId")
                        .HasColumnType("integer")
                        .HasColumnName("ledger_id");

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("TxnDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("txn_date");

                    b.HasKey("Id");

                    b.HasIndex("RecById");

                    b.ToTable("liability", "accounting");
                });

            modelBuilder.Entity("ExpenseTracker.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<bool>("IsReversed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reversed");

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<int?>("ReversedId")
                        .HasColumnType("integer")
                        .HasColumnName("reversed_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("TxnDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("txn_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<string>("VoucherNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("voucher_no");

                    b.Property<int>("VoucherType")
                        .HasColumnType("integer")
                        .HasColumnName("voucher_type");

                    b.HasKey("Id");

                    b.HasIndex("RecById");

                    b.ToTable("transactions", "accounting");
                });

            modelBuilder.Entity("ExpenseTracker.Models.TransactionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CrAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("cr_amount");

                    b.Property<decimal>("DrAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("dr_amount");

                    b.Property<char>("DrCr")
                        .HasColumnType("character(1)")
                        .HasColumnName("dr_cr");

                    b.Property<int>("LedgerId")
                        .HasColumnType("integer")
                        .HasColumnName("ledger_id");

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("RecById");

                    b.HasIndex("TransactionId");

                    b.ToTable("transaction_details", "accounting");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ExpenseTracker.Models.Bank", b =>
                {
                    b.HasOne("ExpenseTracker.Models.AppUser", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecBy");
                });

            modelBuilder.Entity("ExpenseTracker.Models.BankTransaction", b =>
                {
                    b.HasOne("ExpenseTracker.Models.AppUser", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecBy");
                });

            modelBuilder.Entity("ExpenseTracker.Models.Coa", b =>
                {
                    b.HasOne("ExpenseTracker.Models.AppUser", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecBy");
                });

            modelBuilder.Entity("ExpenseTracker.Models.Expense", b =>
                {
                    b.HasOne("ExpenseTracker.Models.Ledger", "Ledger")
                        .WithMany()
                        .HasForeignKey("LedgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseTracker.Models.AppUser", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ledger");

                    b.Navigation("RecBy");
                });

            modelBuilder.Entity("ExpenseTracker.Models.Income", b =>
                {
                    b.HasOne("ExpenseTracker.Models.AppUser", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecBy");
                });

            modelBuilder.Entity("ExpenseTracker.Models.Ledger", b =>
                {
                    b.HasOne("ExpenseTracker.Models.AppUser", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecBy");
                });

            modelBuilder.Entity("ExpenseTracker.Models.Liability", b =>
                {
                    b.HasOne("ExpenseTracker.Models.AppUser", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecBy");
                });

            modelBuilder.Entity("ExpenseTracker.Models.Transaction", b =>
                {
                    b.HasOne("ExpenseTracker.Models.AppUser", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecBy");
                });

            modelBuilder.Entity("ExpenseTracker.Models.TransactionDetail", b =>
                {
                    b.HasOne("ExpenseTracker.Models.AppUser", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseTracker.Models.Transaction", "Transaction")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecBy");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ExpenseTracker.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ExpenseTracker.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseTracker.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ExpenseTracker.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpenseTracker.Models.Transaction", b =>
                {
                    b.Navigation("TransactionDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
